name: Build with JDK 11 on Ubuntu

on:
    push:
        branches:
        - master
    pull_request:
        branches:
        - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v3
        -   name: Set up JDK 11
            uses: actions/setup-java@v3
            with:
                java-version: '11'
                distribution: temurin
                cache: maven
                server-id: github-jackcess                # value of repository/id field of the pom.xml
                server-username: GH_PACKAGE_REPO_USERNAME # env variable name for username
                server-password: GH_PACKAGE_REPO_PASSWORD # env variable name for GitHub Personal Access Token
        -   name: Build with Maven/JDK 11 on Ubuntu
            run: mvn --batch-mode --file pom.xml --activate-profiles github-package-repo-jackcess clean package
            env:
                GH_PACKAGE_REPO_USERNAME: ${{ secrets.GH_PACKAGE_REPO_USERNAME }}
                GH_PACKAGE_REPO_PASSWORD: ${{ secrets.GH_PACKAGE_REPO_PASSWORD }}}
    deploy_deploy_sonatype:
        needs: build
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v3
        -   name: Set up JDK 11
            uses: actions/setup-java@v3
            with:
                java-version: '11'
                distribution: temurin
                cache: maven
                # must match distributionManagement/snapshotRepository/id in pom:
                server-id: sonatype-nexus-snapshots
                server-username: SONATYPE_OSSRH_USERNAME
                server-password: SONATYPE_OSSRH_PASSWORD
        -   name: Build with Maven/JDK 11 on Ubuntu
            run: mvn --batch-mode --file pom.xml --activate-profiles fast,github-package-repo-jackcess deploy
            env:
                SONATYPE_OSSRH_USERNAME:  ${{ secrets.SONATYPE_OSSRH_USERNAME }}
                SONATYPE_OSSRH_PASSWORD:  ${{ secrets.SONATYPE_OSSRH_PASSWORD }}
